# fly.toml app configuration file generated for tx-parser-go on 2024-12-05T23:26:21+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tx-parser-go'
primary_region = 'hkg'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[env]
PUBLIC_NODE_URL = "https://ethereum-rpc.publicnode.com/"
PORT = "8080"
JOB_SCHEDULE = "1s"
USE_DATABASE = "true"
POSTGRES_USER = "tx_parser_go"
POSTGRES_DATABASE = "tx_parser_go"
POSTGRES_HOST = "tx-parser-db.flycast"
POSTGRES_PORT = "5432"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[checks]
[checks.http_health_check]
port = 8080
type = 'http'
interval = '15s'
timeout = '10s'
grace_period = '30s'
method = 'get'
path = '/healthz'
